name: CI/CD for Node.js Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Initializing CI/CD pipeline..."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Depot CLI
        id: cache-depot
        uses: actions/cache@v3
        with:
          path: ~/.depot
          key: ${{ runner.os }}-depot-cli

      - name: Install Depot CLI
        if: steps.cache-depot.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://depot.dev/install.sh | sh
          export PATH=$HOME/.depot/bin:$PATH
          echo "Depot CLI installed and added to PATH."

      - name: Verify Depot CLI Installation
        run: depot --version  # This will confirm if Depot is installed successfully

      - name: Authenticate Depot
        run: depot auth login --token ${{ secrets.DEPOT_TOKEN }}

      - name: Install Dependencies with Depot Cache
        run: |
          if [ -d "node_modules" ]; then
            echo "✅ Cache hit! Using cached dependencies."
          else
            echo "❌ Cache miss! Installing dependencies from scratch."
          fi
          depot exec npm install

      - name: Build Application
        run: |
          if [ -d "dist" ]; then
            echo "✅ Cache hit! Using cached build."
          else
            echo "❌ Cache miss! Rebuilding application."
          fi
          depot exec npm run build

      - name: Run Tests
        run: depot exec npm test

      - name: Complete Job
        run: echo "Build & Test Completed!"
