name: CI/CD for Node.js Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Initializing CI/CD pipeline..."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules with Depot (without installing Depot CLI)
        id: cache-depot
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies (only if needed)
        if: steps.cache-depot.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Application
        run: |
          if [ -d "dist" ]; then
            echo "✅ Cache hit! Using cached build."
          else
            echo "❌ Cache miss! Rebuilding application."
          fi
          npm run build

      - name: Run Tests
        run: npm test

      - name: Complete Job
        run: echo "Build & Test Completed!"
